services:
  web:
    image: nginx:1.27-alpine
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas:  5
      restart_policy:
        condition: on-failure
    networks:
      - web-net
networks:
  web-net:
